name: Deploy WP & Nextjs to Production - builds and deploys
on:
  push:
    branches:
      - 'production'
    # # Only run workflow if push a server tag
    # tags:
    #   - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  should_deploy_wp:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' # If it's a pull request we don't want to deploy wordpress
    outputs:
      should_deploy: ${{ steps.changed_files_wp.outputs.any_changed }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - id: check_secrets
        uses: svrooij/secret-gate-action@v1
        with:
          inputsToCheck: 'PRODUCTION_BE_SSH_USER,PRODUCTION_BE_SSH_HOST,PRODUCTION_BE_SSH_PORT,SSH_PRIVATE_KEY,PRODUCTION_WORDPRESS_PATH,PRODUCTION_NEXT_URL,WORDPRESS_THEME_NAME'
        env:
          PRODUCTION_BE_SSH_USER: ${{ secrets.PRODUCTION_BE_SSH_USER }}
          PRODUCTION_BE_SSH_HOST: ${{ secrets.PRODUCTION_BE_SSH_HOST }}
          PRODUCTION_BE_SSH_PORT: ${{ secrets.PRODUCTION_BE_SSH_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PRODUCTION_WORDPRESS_PATH: ${{ secrets.PRODUCTION_WORDPRESS_PATH }}
          PRODUCTION_NEXT_URL: ${{ secrets.PRODUCTION_NEXT_URL }}
          WORDPRESS_THEME_NAME: ${{ secrets.WORDPRESS_THEME_NAME }}

      - name: Set output
        if: steps.check_secrets.outputs.inputsChecked == 'true'
        run: echo "should_deploy=${{ steps.check_secrets.outputs.inputsChecked }}" >> $GITHUB_OUTPUT

  deploy_wp:
    needs: should_deploy_wp
    if: needs.should_deploy_wp.outputs.should_deploy == 'true'
    uses: ./.github/workflows/deploy-wp.yml
    secrets:
      SSH_USER: ${{ secrets.PRODUCTION_BE_SSH_USER }}
      SSH_HOST: ${{ secrets.PRODUCTION_BE_SSH_HOST }}
      SSH_PORT: ${{ secrets.PRODUCTION_BE_SSH_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      WORDPRESS_PATH: ${{ secrets.PRODUCTION_WORDPRESS_PATH }}
      NEXT_URL: ${{ secrets.PRODUCTION_NEXT_URL }}
      WORDPRESS_THEME_NAME: ${{ secrets.WORDPRESS_THEME_NAME }}

  deploy_next:
    runs-on: ubuntu-latest
    needs: deploy_wp
    if: ${{ always() }} # Always run the job regardless if build_deploy_wp was successful/skip or not
    steps:
      - uses: actions/checkout@v3
      - name: Deploy NextJS
        uses: ./.github/actions/deploy-vercel
        with:
          GITHUB_TOKEN: ${{ github.token }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          GITHUB_DEPLOYMENT_ENV: Production
          PRODUCTION: true
