name: Deploy WP & Nextjs to Staging - builds and deploys
on:
  # Only run workflow if push to branch
  push:
    branches:
      - '!production'

  # Run workflow for pull requests as well
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  should_deploy_wp:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.ref_name == 'main' # run only if not pull_request & on main branch
    outputs:
      should_deploy: ${{ steps.changed_files_wp.outputs.any_changed }}
    steps:
      - id: check_secrets
        uses: svrooij/secret-gate-action@v1
        with:
          inputsToCheck: 'STAGING_BE_SSH_USER,STAGING_BE_SSH_HOST,STAGING_BE_SSH_PORT,SSH_PRIVATE_KEY,STAGING_WORDPRESS_PATH,STAGING_NEXT_URL,WORDPRESS_THEME_NAME'
        env:
          STAGING_BE_SSH_USER: ${{ secrets.STAGING_BE_SSH_USER }}
          STAGING_BE_SSH_HOST: ${{ secrets.STAGING_BE_SSH_HOST }}
          STAGING_BE_SSH_PORT: ${{ secrets.STAGING_BE_SSH_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          STAGING_WORDPRESS_PATH: ${{ secrets.STAGING_WORDPRESS_PATH }}
          STAGING_NEXT_URL: ${{ secrets.STAGING_NEXT_URL }}
          WORDPRESS_THEME_NAME: ${{ secrets.WORDPRESS_THEME_NAME }}

      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: changed_files_wp
        if: steps.check_secrets.outputs.inputsChecked == 'true'
        uses: tj-actions/changed-files@v34
        with:
          since_last_remote_commit: 'true'
          files: |
            wordpress/**

      - name: Set output
        if: steps.check_secrets.outputs.inputsChecked == 'true'
        run: echo "should_deploy=${{ steps.changed_files_wp.outputs.any_changed }}" >> $GITHUB_OUTPUT

  deploy_wp:
    needs: should_deploy_wp
    if: needs.should_deploy_wp.outputs.should_deploy == 'true'
    uses: ./.github/workflows/deploy-wp.yml
    secrets:
      SSH_USER: ${{ secrets.STAGING_BE_SSH_USER }}
      SSH_HOST: ${{ secrets.STAGING_BE_SSH_HOST }}
      SSH_PORT: ${{ secrets.STAGING_BE_SSH_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      WORDPRESS_PATH: ${{ secrets.STAGING_WORDPRESS_PATH }}
      NEXT_URL: ${{ secrets.STAGING_NEXT_URL }}
      WORDPRESS_THEME_NAME: ${{ secrets.WORDPRESS_THEME_NAME }}

  deploy_next:
    runs-on: ubuntu-latest
    needs: deploy_wp
    if: ${{ always() }} # Always run the job regardless if build_deploy_wp was successful/skip or not
    steps:
      - uses: actions/checkout@v3
      - name: Deploy NextJS
        uses: ./.github/actions/deploy-vercel
        with:
          GITHUB_TOKEN: ${{ github.token }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          GITHUB_DEPLOYMENT_ENV: Preview
          PRODUCTION: false
